mysql -u root -e "CREATE DATABASE ask;"
mysql -u root -e "SET GLOBAL validate_password_special_char_count = 0;"
mysql -u root -e "SET GLOBAL validate_password_number_count = 0;"
mysql -u root -e "SET GLOBAL validate_password_mixed_case_count = 0;"
mysql -u root -e "SET GLOBAL validate_password_length = 0;"
mysql -u root -e "SET GLOBAL validate_password_policy = 0;"
mysql -u root -e "CREATE USER 'snezhh'@'localhost';"
mysql -u root -e "GRANT ALL ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT CREATE ROUTINE ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT CREATE TABLESPACE ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT CREATE USER ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT FILE ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT PROCESS ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT RELOAD ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT REPLICATION CLIENT ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT REPLICATION SLAVE ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT SHOW DATABASES ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT SHUTDOWN ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "GRANT SUPER ON *.* TO 'snezhh'@'localhost';"
mysql -u root -e "FLUSH PRIVILEGES;"
