mysql -u root -e "CREATE DATABASE ask;"
mysql -u root -e "CREATE USER snezhh"
mysql -u root -e "GRANT ALL ON *.* TO snezhh;"
mysql -u root -e "GRANT CREATE ROUTINE ON *.* TO snezhh;"
mysql -u root -e "GRANT CREATE TABLESPACE ON *.* TO snezhh;"
mysql -u root -e "GRANT CREATE USER ON *.* TO snezhh;"
mysql -u root -e "GRANT FILE ON *.* TO snezhh;"
mysql -u root -e "GRANT PROCESS ON *.* TO snezhh;"
mysql -u root -e "GRANT RELOAD ON *.* TO snezhh;"
mysql -u root -e "GRANT REPLICATION CLIENT ON *.* TO snezhh;"
mysql -u root -e "GRANT REPLICATION SLAVE ON *.* TO snezhh;"
mysql -u root -e "GRANT SHOW DATABASES ON *.* TO snezhh;"
mysql -u root -e "GRANT SHUTDOWN ON *.* TO snezhh;"
mysql -u root -e "GRANT SUPER ON *.* TO snezhh;"
mysql -u root -e "FLUSH PRIVILEGES;"
